// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0mArFqBOatI_-XPFnKIuMgjylfh9vLCw',
    appId: '1:809718584629:web:0603916dd8c692a3b6287c',
    messagingSenderId: '809718584629',
    projectId: 'ahenwada',
    authDomain: 'ahenwada.firebaseapp.com',
    storageBucket: 'ahenwada.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCelm3AFKueLQe4OoNKJFYBu3lTMamDvT4',
    appId: '1:809718584629:android:155211dada9c36eab6287c',
    messagingSenderId: '809718584629',
    projectId: 'ahenwada',
    storageBucket: 'ahenwada.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBv51dJJeLXW02Vt401K4vkVp2AkPUeABs',
    appId: '1:809718584629:ios:f38d864675d651a4b6287c',
    messagingSenderId: '809718584629',
    projectId: 'ahenwada',
    storageBucket: 'ahenwada.appspot.com',
    androidClientId: '809718584629-r0fanv8msg53e00dqraj7c3848c8aoju.apps.googleusercontent.com',
    iosClientId: '809718584629-3umduqmpedmrcdrce1kg0f1tri5dniig.apps.googleusercontent.com',
    iosBundleId: 'com.example.dogFoodApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBv51dJJeLXW02Vt401K4vkVp2AkPUeABs',
    appId: '1:809718584629:ios:f38d864675d651a4b6287c',
    messagingSenderId: '809718584629',
    projectId: 'ahenwada',
    storageBucket: 'ahenwada.appspot.com',
    androidClientId: '809718584629-r0fanv8msg53e00dqraj7c3848c8aoju.apps.googleusercontent.com',
    iosClientId: '809718584629-3umduqmpedmrcdrce1kg0f1tri5dniig.apps.googleusercontent.com',
    iosBundleId: 'com.example.dogFoodApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0mArFqBOatI_-XPFnKIuMgjylfh9vLCw',
    appId: '1:809718584629:web:8da4ed6a89a7a85cb6287c',
    messagingSenderId: '809718584629',
    projectId: 'ahenwada',
    authDomain: 'ahenwada.firebaseapp.com',
    storageBucket: 'ahenwada.appspot.com',
  );
}
